name = "LineIntersections"
uuid = "125b3fd6-e0d7-405d-ad3f-b214ae047a8d"
authors = ["Simon <simon.coste@inria.fr> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
